testapplication:
  replicaCount: 1
  image:
    repository: github.com/baldummy/app-repo.git
    tag: 1.1.0
  network:
    http:
      servicePort: 8080
      ingress:
        host: client-libraries-test123.shapp-test.os1.balgroupit.com
  readinessProbe:
    httpGet:
      path: /
      port: http
  livenessProbe:
    httpGet:
      path: /
      port: http
