testapplication:
  replicaCount: 1
  image:
    repository: github.com/baldummy/app-repo.git
    tag: 2304a41529ac33c55b78977b9e3e5f870b349ca1
  network:
    http:
      servicePort: 8080
      ingress:
        host: client-libraries-f601adbb.shapp-test.os1.balgroupit.com
  readinessProbe:
    httpGet:
      path: /
      port: http
  livenessProbe:
    httpGet:
      path: /
      port: http
