testapplication:
  replicaCount: 1
  image:
    repository: github.com/baldummy/app-repo.git
    tag: 064db8f30c4ca27ef44a9f1195ff3a0b6a7dcdcb
  network:
    http:
      servicePort: 8080
      ingress:
        host: client-libraries-test123yyy.shapp-test.os1.balgroupit.com
  readinessProbe:
    httpGet:
      path: /
      port: http
  livenessProbe:
    httpGet:
      path: /
      port: http
